# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "shu-san-scripts"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Love"]
  s.date = "2011-09-24"
  s.description = "See the README file."
  s.email = "david@homeunix.org.uk"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.homepage = "http://github.com/dlove24/shu-san-scripts"
  s.licenses = ["ISC"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Scripts used to set-up and manage iSCSI targets on OpenSolaris (ZFS) systems."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<cri>, ["~> 2.0.2"])
      s.add_runtime_dependency(%q<facets>, [">= 2.4"])
      s.add_runtime_dependency(%q<uuidtools>, ["~> 2.1.2"])
      s.add_runtime_dependency(%q<ansi>, [">= 1.2"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<vclog>, ["~> 1.8.1"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<riot>, [">= 0"])
    else
      s.add_dependency(%q<cri>, ["~> 2.0.2"])
      s.add_dependency(%q<facets>, [">= 2.4"])
      s.add_dependency(%q<uuidtools>, ["~> 2.1.2"])
      s.add_dependency(%q<ansi>, [">= 1.2"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<vclog>, ["~> 1.8.1"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<riot>, [">= 0"])
    end
  else
    s.add_dependency(%q<cri>, ["~> 2.0.2"])
    s.add_dependency(%q<facets>, [">= 2.4"])
    s.add_dependency(%q<uuidtools>, ["~> 2.1.2"])
    s.add_dependency(%q<ansi>, [">= 1.2"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<vclog>, ["~> 1.8.1"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<riot>, [">= 0"])
  end
end

